// <auto-generated />
using System;
using System.Text.Json;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Infrastructure.Data.Entities.WheelEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("ActiveOptionAfter")
                        .HasColumnType("smallint");

                    b.Property<short?>("ActiveOptionBefore")
                        .HasColumnType("smallint");

                    b.Property<short?>("CloseReason")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("CostBasisAfter")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("CostBasisBefore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<JsonDocument>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SharesOwnedAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("SharesOwnedBefore")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MetadataJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadataJson"), "gin");

                    b.HasIndex("Ticker");

                    b.HasIndex("Ticker", "OccurredAtUtc");

                    b.ToTable("wheel_events", (string)null);
                });

            modelBuilder.Entity("Backend.Infrastructure.Data.Entities.WheelTickerStateEntity", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<short>("ActiveOption")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("CostBasis")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly?>("Expiration")
                        .HasColumnType("date");

                    b.Property<bool>("HasShares")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OpenPremium")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset?>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SharesOwned")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Strike")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Ticker");

                    b.ToTable("wheel_ticker_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
